[package]
name = "horsenuggets/assetfile"
description = "Finally, a way to work with Roblox assets local to your computer."
version = "0.0.1"
private = true
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/horsenuggets/assetfile"

[dependencies]
Commandline = "horsenuggets/commandline-luau@0.0.11"
Dotenv = "horsenuggets/dotenv-luau@0.0.2"
HashLib = "horsenuggets/hashlib@0.0.2"
t = "horsenuggets/t@3.1.1-horse.0.3"

[dev-dependencies]
Testable = "horsenuggets/testable@0.1.0"
